controller:
  metrics:
    enabled: true
    bindAddress: 0.0.0.0

    service:
      create: true
      port: 10254
      targetPort: 10254

    serviceMonitor:
      enabled: true
      namespace: monitoring
      namespaceSelector:
        matchNames:
          - ingress-nginx
      additionalLabels:
        release: monitoring