{{- if .Values.billingService.enabled }}
{{- $ext := default (dict "enabled" false "name" "") .Values.externalJwtSecret -}}
{{- $res := .Values.billingService.resources | default .Values.resources -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  labels:
    {{- include "docker-homework-app.labels" . | nindent 4 }}
    app: billing-service
    app.kubernetes.io/part-of: docker-homework-app
    app.kubernetes.io/component: billing
spec:
  replicas: {{ .Values.billingService.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        {{- include "docker-homework-app.labels" . | nindent 8 }}
        app: billing-service
        app.kubernetes.io/part-of: docker-homework-app
        app.kubernetes.io/component: billing
      annotations:
        {{- if not $ext.enabled }}
        checksum/jwt-secret: {{ include (print $.Template.BasePath "/jwt-secret.yaml") . | sha256sum }}
        {{- end }}
    spec:
      containers:
        - name: billing-service
          image: "{{ .Values.billingService.image.repository }}:{{ .Values.billingService.image.tag }}"
          imagePullPolicy: {{ .Values.billingService.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.billingService.containerPort }}
          env:
            - name: DbSettings__Host
              value: {{ .Values.pg.config.host | quote }}
            - name: DbSettings__Port
              value: "{{ .Values.pg.config.port }}"
            - name: DbSettings__Database
              value: {{ .Values.pg.services.billing.database | quote }}
            - name: DbSettings__Username
              value: {{ .Values.pg.services.billing.username | quote }}
            - name: DbSettings__Password
              value: {{ .Values.pg.services.billing.password | quote }}

          envFrom:
            - secretRef:
                name: {{ if $ext.enabled }}{{ $ext.name }}{{ else }}{{ printf "%s-jwt-secret" (include "docker-homework-app.fullname" .) }}{{ end }}

          resources:
            {{- toYaml $res | nindent 12 }}
{{- end }}