{{- $ext := default (dict "enabled" false "name" "") .Values.externalJwtSecret -}}
{{- $pgSecretName := (.Values.pg.app.secretName | default (printf "%s-pg-secret" (include "docker-homework-app.fullname" .))) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-homework-app.fullname" . }}
  labels:
    {{- include "docker-homework-app.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: docker-homework-app
    app.kubernetes.io/component: app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "docker-homework-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "docker-homework-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/part-of: docker-homework-app
        app.kubernetes.io/component: app
      annotations:
        checksum/pg-secret: {{ include (print $.Template.BasePath "/pg-secret.yaml") . | sha256sum }}
        {{- if not $ext.enabled }}
        checksum/jwt-secret: {{ include (print $.Template.BasePath "/jwt-secret.yaml") . | sha256sum }}
        {{- end }}
    spec:
      serviceAccountName: {{ default (include "docker-homework-app.fullname" .) .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          env:
            - name: Billing__BaseUrl
              value: "http://billing-service"
          envFrom:
            - secretRef:
                name: {{ $pgSecretName }}
            - secretRef:
                name: {{ if $ext.enabled }}{{ $ext.name }}{{ else }}{{ printf "%s-jwt-secret" (include "docker-homework-app.fullname" .) }}{{ end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}