apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-homework-app.fullname" . }}-init-sql
  labels:
    {{- include "docker-homework-app.labels" . | nindent 4 }}
data:
  init.sql: |
{{ tpl (.Files.Get "init/init.sql") . | indent 4 }}