{{- if .Values.orderService.enabled }}
{{- $ext := default (dict "enabled" false "name" "") .Values.externalJwtSecret -}}
{{- $res := .Values.orderService.resources | default .Values.resources -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    {{- include "docker-homework-app.labels" . | nindent 4 }}
    app: order-service
    app.kubernetes.io/part-of: docker-homework-app
    app.kubernetes.io/component: order
spec:
  replicas: {{ .Values.orderService.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        {{- include "docker-homework-app.labels" . | nindent 8 }}
        app: order-service
        app.kubernetes.io/part-of: docker-homework-app
        app.kubernetes.io/component: order
      annotations:
        {{- if not $ext.enabled }}
        checksum/jwt-secret: {{ include (print $.Template.BasePath "/jwt-secret.yaml") . | sha256sum }}
        {{- end }}
    spec:
      containers:
        - name: order-service
          image: "{{ .Values.orderService.image.repository }}:{{ .Values.orderService.image.tag }}"
          imagePullPolicy: {{ .Values.orderService.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.orderService.containerPort }}

          env:
            - name: DbSettings__Host
              value: {{ .Values.pg.config.host | quote }}
            - name: DbSettings__Port
              value: "{{ .Values.pg.config.port }}"
            - name: DbSettings__Database
              value: {{ .Values.pg.services.order.database | quote }}
            - name: DbSettings__Username
              value: {{ .Values.pg.services.order.username | quote }}
            - name: DbSettings__Password
              value: {{ .Values.pg.services.order.password | quote }}
            - name: Billing__BaseUrl
              value: "http://billing-service"
            - name: Notifications__BaseUrl
              value: "http://notification-service"
            - name: Warehouse__BaseUrl
              value: "http://warehouse-service"
            - name: Delivery__BaseUrl
              value: "http://delivery-service"

          envFrom:
            - secretRef:
                name: {{ if $ext.enabled }}{{ $ext.name }}{{ else }}{{ printf "%s-jwt-secret" (include "docker-homework-app.fullname" .) }}{{ end }}

          readinessProbe:
            httpGet:
              path: /orders/health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /orders/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            {{- toYaml $res | nindent 12 }}

{{- end }}