apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-homework-app.fullname" . }}
  labels:
    {{- include "docker-homework-app.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: docker-homework-app
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "docker-homework-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app
