{{- if and .Values.monitoring.enabled .Values.monitoring.pgExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-homework-app.fullname" . }}-pg-exporter
  labels:
    {{- include "docker-homework-app.labels" . | nindent 4 }}
    app: pg-exporter
    app.kubernetes.io/part-of: docker-homework-app
    app.kubernetes.io/component: monitoring
spec:
  replicas: {{ .Values.monitoring.pgExporter.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: pg-exporter
  template:
    metadata:
      labels:
        {{- include "docker-homework-app.labels" . | nindent 8 }}
        app: pg-exporter
        app.kubernetes.io/part-of: docker-homework-app
        app.kubernetes.io/component: monitoring
      annotations:
        checksum/pg-exporter-secret: {{ include (print $.Template.BasePath "/monitoring/pg-exporter-secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: pg-exporter
          image: "{{ .Values.monitoring.pgExporter.image.repository }}:{{ .Values.monitoring.pgExporter.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-metrics
              containerPort: {{ .Values.monitoring.pgExporter.service.targetPort }}
          envFrom:
            - secretRef:
                name: {{ include "docker-homework-app.fullname" . }}-pg-exporter
          resources:
            {{- toYaml (.Values.monitoring.pgExporter.resources | default dict) | nindent 12 }}
{{- end }}