{{- if and .Values.monitoring.enabled .Values.monitoring.pgExporter.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "docker-homework-app.fullname" . }}-pg-exporter
  labels:
    {{- include "docker-homework-app.labels" . | nindent 4 }}
    {{- toYaml .Values.monitoring.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: pg-exporter
  endpoints:
    - port: {{ .Values.monitoring.pgExporter.service.name | default "http-metrics" }}
      interval: {{ .Values.monitoring.serviceMonitor.interval | default "15s" }}
{{- end }}