{{- if and .Values.monitoring.enabled .Values.monitoring.pgExporter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-homework-app.fullname" . }}-pg-exporter
  labels:
    {{- include "docker-homework-app.labels" . | nindent 4 }}
    app: pg-exporter
    app.kubernetes.io/part-of: docker-homework-app
    app.kubernetes.io/component: monitoring
type: Opaque
stringData:
  DATA_SOURCE_NAME: >-
    postgresql://{{ .Values.monitoring.pgExporter.secret.username }}:{{ .Values.monitoring.pgExporter.secret.password }}
    @{{ .Values.pg.config.host }}:{{ .Values.pg.config.port }}/postgres?sslmode=disable
{{- end }}