apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-homework-app.fullname" . }}-pg-exporter
type: Opaque
stringData:
  DATA_SOURCE_NAME: {{ printf "postgresql://%s:%s@%s:%v/postgres?sslmode=disable" .Values.monitoring.pgExporter.secret.username .Values.monitoring.pgExporter.secret.password .Values.pg.config.host .Values.pg.config.port | quote }}