{{- if and .Values.monitoring.enabled .Values.monitoring.pgExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-homework-app.fullname" . }}-pg-exporter
  labels:
    {{- include "docker-homework-app.labels" . | nindent 4 }}
    app: pg-exporter
    app.kubernetes.io/part-of: docker-homework-app
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  selector:
    app: pg-exporter
  ports:
    - name: {{ .Values.monitoring.pgExporter.service.name | default "http-metrics" }}
      port: {{ .Values.monitoring.pgExporter.service.port }}
      targetPort: http-metrics
{{- end }}