{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled (.Values.monitoring.appMetrics.enabled | default false) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "docker-homework-app.fullname" . }}-app
  labels:
    {{- include "docker-homework-app.labels" . | nindent 4 }}
    {{- toYaml .Values.monitoring.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "docker-homework-app.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: {{ .Values.monitoring.appMetrics.portName | default "http" }}
      path: {{ .Values.monitoring.appMetrics.path | default "/metrics" }}
      interval: {{ .Values.monitoring.serviceMonitor.interval | default "15s" }}
{{- end }}