{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled .Values.monitoring.appMetrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "docker-homework-app.fullname" . }}-apps
  labels:
    {{- include "docker-homework-app.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.monitoring.serviceMonitor.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "docker-homework-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: {{ .Values.monitoring.appMetrics.portName | default "http" }}
      path: {{ .Values.monitoring.appMetrics.path | default "/metrics" }}
      interval: {{ .Values.monitoring.serviceMonitor.interval | default "15s" }}
{{- end }}